// flow-typed signature: f4309b456c84a322d0dcc3b5d363f579
// flow-typed version: <<STUB>>/reason-js_v^0.3.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reason-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reason-js' {
  declare module.exports: any;
}
